### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by ashi20192020**

### CODE REVIEW

**Comment by GopherJ** [comment]
@ashi20192020ayush can you check if v0.9.10 works ? because statemine doesn't produce blocks yet

**Comment by ETeissonniere** [comment]
Shouldn't we update the relay chain too?

**Comment by GopherJ** [comment]
@ashi20192020ayush pls check this https://github.com/parallel-finance/parallel/issues/705, it doesn't produce blocks yet

**Comment by ashi20192020ayush** [comment]
@GopherJ I started getting different error while hitting `sudo make launch`.

image

I followed the steps mentioned here https://github.com/parallel-finance/parallel/pull/715#issuecomment-945354329 but still not able to connect.

**Comment by GopherJ** [comment]
> @GopherJ I started getting different error while hitting `sudo make launch`.
> 
> image
> 
> I followed the steps mentioned here [#715 (comment)](https://github.com/parallel-finance/parallel/pull/715#issuecomment-945354329) but still not able to connect.

let's maybe forget this task for now

**Pull request closed without merging**
