### PR TITLE
Feat/liquid staking v3

### PR DESCRIPTION
**Pull request by GopherJ**

### CODE REVIEW

**Comment by yz89** [comment]
We don't need to maintain more pallets at the same time. 'liquid-staking' should be considered final, supporting XCm-transact.

**Comment by GopherJ** [comment]
> We don't need to maintain more pallets at the same time. 'liquid-staking' should be considered final, supporting XCm-transact.

so you want to reuse `liquid-staking v1` for testing xcm.transact? I thought we don't want to touch it

**Comment by yz89** [comment]
Yes, you can delete all the code in `liquid-staking` and rename `liquid-staking-v3` to `liquid-staking`.

**Comment by GopherJ** [comment]
> Yes, you can delete all the code in `liquid-staking` and rename `liquid-staking-v3` to `liquid-staking`.

ok I'll test runtime upgrade

**Comment by MrPai** [comment]
> Yes, you can delete all the code in `liquid-staking` and rename `liquid-staking-v3` to `liquid-staking`.

Shall we keep on the job according to this PR, or raise a new PR?

**Pull request merged**
