### PR TITLE
Feature/parallel stableswap

### PR DESCRIPTION
**Pull request by c02fee**
StableSwap Pallet Implementation 

- [x] New Pallet for stable swap
- [x] Move code from AMM
- [x] Add and update unit tests
- [x] BigUInt conversion 
- [ ] Allow unsigned transactions ?
- [x] Fix DispatchError type Error 
- [x] Fix Vanilla Runtime Error
- [x]  create_pool
- [x]  add_liquidity
- [x]  remove_liquidity
- [x] do_swap
- [x]  get_reserves

### CODE REVIEW

**Comment by c02fee** [comment]
@drbh  Needs input for the

- [ ] Router implementation 
- [ ] Non callable implementation

**Comment by drbh** [comment]
@c02fee this looks great! some changes we'll need to make

- [ ] instead of importing the AMM into this pallet we'll want to implement all of the same calls
    - [ ] create_pool
    - [ ] add_liquidity
    - [ ] remove_liquidity
    - [ ] do_swap
    - [ ] get_reserves
   
- [ ] add a new pool type that support the variables needed for stable swap

 We can focus on the fee generating functions after we have the core functions added. A lot of this will be able to be copied over - but we'll have to make some update to the amplification value when liquidity is added/removed. 

Can you add the functions above and remove the `AMM` config variable? 

PS soon I'll be shifting most of my focus to this pallet and we can get all of these features added together 🙂

**Comment by c02fee** [comment]
@drbh Yep sure , Cheers! 🥂

**Comment by drbh** [comment]
TODO
- [ ] update `d` when liquidity is added/removed
- [ ] update `get_amount_out` and `get_amount_in` for new swap values
- [ ] make sure this matches other stable swaps
- [ ] update pool type to have `d` or `A` or other variables that are used in stableswap

**Comment by c02fee** [comment]
Addressed via :- https://github.com/parallel-finance/parallel/pull/1633

**Pull request closed without merging**
