### PR TITLE
test try-runtime-bot

### PR DESCRIPTION
**Pull request by woshihahaha**

### CODE REVIEW

**Comment by c0ding** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain vanilla-dev on-runtime-upgrade live --uri ws://vanilla

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain vanilla on-runtime-upgrade live --uri ws://vanilla

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerr on-runtime-upgrade live --uri ws://kerria

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by c0ding** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain kerria-dev on-runtime-upgrade live --uri ws://kerria

**Comment by woshihahaha** [comment]
/try-runtime queue --chain heiko-dev on-runtime-upgrade live --uri ws://heiko

**Comment by woshihahaha** [comment]
/try-runtime queue --chain parallel-dev on-runtime-upgrade live --uri ws://parallel

**Comment by woshihahaha** [comment]
/try-runtime queue --chain vanilla-dev on-runtime-upgrade live --uri ws://vanilla

**Pull request closed without merging**
