### PR TITLE
VaultToken/LPVaultToken Price feeder

### PR DESCRIPTION
**Pull request by yrong**
- Context

Previously we use some offchain-oracle-client to feed price based on AMM and this PR aims to introduce another way to calculate price of VaultToken(or CToken) and VaultLPToken purely on chain, and this is a subtask/dependency of the liquidation-free design of VaultToken in Money Market

ExchangeRate from VaultToken to RelayToken:
image

ExchangeRate of LPVaultToken to RelayToken:
image

- Revamp/Refactor including

crowdloan:
- Add `LeasePeriod` as const(same as relaychain) as to calculate `VaultTokenExchangeRate` later
- Add impl for `VaultTokenExchangeRateProvider`

amm:
- Expose api to get pool by lp_asset_id so to filter by `VaultToken` and calc price of `LPVaultToken` later
- Move/promote `Pool` structure to common 

Todo List:
- [x] vault_token price feeder
- [x] lp_vault_token price feeder
- [x] more tests
- [x] improve error handling & log
- [x] integration tests

### CODE REVIEW

**Comment by yrong** [comment]
https://github.com/parallel-finance/parallel/pull/1742

**Comment by yrong** [comment]
@GopherJ in recent [commit](https://github.com/parallel-finance/parallel/pull/1715/commits/519ee3218d83e7152ad60fff8d1eafc440090b4c) when trying to fix ci error i've introduced another profile for production which enables some compile flags like `lto`, still not sure how much will gain for performance perspective so not enable it by default when building image. Let me know what you think and we can improve the binary later in future pr if necessary

**Review by alannotnerd — COMMENTED** [review]
LGTM

**Review by GopherJ — APPROVED** [review]

**Comment by yrong** [comment]
@yz89 conflict resolved should be ready to merge

**Pull request merged**
