### PR TITLE
Impl `ptoken` in money market

### PR DESCRIPTION
**Pull request by 0xrjman**
Close
- #334 
- #717

### CODE REVIEW

**Comment by yz89** [comment]
> `fungible::tokens::Inspect` must be implemented before `tokens::Transfer`, is `Transfer` required? It may bring useless `Inspect` implementations in code

Yes, The `Transfer` trait is required by another pallet. Let's discuss how to implement the `Inspect` trait.

**Comment by yz89** [comment]
Pls update the launch script as well.

**Comment by yz89** [comment]
add unit test for every fungible Trait method.

**Comment by alannotnerd** [comment]
I guess we need to test more edge cases. @rjman-ljm

**Comment by rjman-ljm** [comment]
Nice refactoring！

**Comment by rjman-ljm** [comment]
I will follow up and add some edge tests

**Comment by GopherJ** [comment]
other than the comments, it look good to me

**Pull request merged**
