### PR TITLE
Added Amounts in AMM pallet's events

### PR DESCRIPTION
**Pull request by c02fee**

### CODE REVIEW

**Comment by c02fee** [comment]
@GopherJ  
@drbh 
After adding amounts to Events in AMM pallet
Can see a test failure in Benchmark test

`test benchmarking::benchmark_tests::test_benchmarks ... FAILED`
Failure
```
  left: `Event::AMM(Event::LiquidityRemoved(AccountId(15276289921735352792), 1001, 99666, 101, 897000))`,
 right: `Event::AMM(Event::LiquidityRemoved(AccountId(15276289921735352792), 1001, 100000, 101, 900000))`', 
```
Failure link :- https://github.com/parallel-finance/parallel/runs/4881294680?check_suite_focus=true#step:11:494 
 The code which added amounts
 ```
Self::deposit_event(Event::<T, I>::LiquidityRemoved(
  who,
  base_asset,
  base_amount,
  quote_asset,
  quote_amount,
));
 ```

**Comment by c02fee** [comment]
and when I changed to 
liquidity_amount.base_amount, and liquidity_amount.base_amount, liquidity_amount.quote_amount
ended up in the following failure

```
 running 20 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
failing benchmark tests:
test tests::add_liquidity_by_another_user_should_work ... ok
thread 'benchmarking::benchmark_tests::test_benchmarks' panicked at 'assertion failed: `(left == right)`
  left: `Event::AMM(Event::LiquidityRemoved(AccountId(15276289921735352792), 1001, 334, 101, 3000))`,
 right: `Event::AMM(Event::LiquidityRemoved(AccountId(15276289921735352792), 1001, 100000, 101, 900000))`', /home/runner/.cargo/git/checkouts/substrate-7e08433d4c370a21/fcc54a7/frame/system/src/lib.rs:1459:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
remove_liquidity: Any { .. }
create_pool: "PoolAlreadyExists"
thread 'benchmarking::benchmark_tests::test_benchmarks' panicked at 'assertion failed: !anything_failed', pallets/amm/src/benchmarking.rs:129:1
test benchmarking::benchmark_tests::test_benchmarks ... FAILED
```

@drbh @GopherJ @ayushmishra2005

**Comment by GopherJ** [comment]
let me check this today

**Comment by drbh** [comment]
@c02fee it looks like the values didn't match because there are some calculations inside of the `remove_liquidity` that weren't accounted for inside of the benchmark file. 

In order to get the correct amount we need to reproduce the calculations like

```rust
let total_ownership = T::Assets::total_issuance(ASSET_ID);

let ownership_to_remove = 300_000u128 - MINIMUM_LIQUIDITY;

// get expected value by doing the same calculations inside of the `remove_liquidity` function
let expected_base_amount = ownership_to_remove
    .saturating_mul(base_amount)
    .checked_div(total_ownership)
    .unwrap();

let expected_quote_amount = ownership_to_remove
    .saturating_mul(quote_amount)
    .checked_div(total_ownership)
    .unwrap();
``` 

after the pool has been created. Please see the changes I made to the PR

**Comment by drbh** [comment]
however, I'm not sure if we should merge these changes because of some larger refactoring happening to the AMM pallet inside of this PR https://github.com/parallel-finance/parallel/pull/1207 

I think we should merge #1207 first, then port this work over once the refactoring is finished in order to avoid complicated merge conflicts

**Comment by GopherJ** [comment]
This is solved in #1207

**Pull request closed without merging**
