### PR TITLE
Feat/update event syntax

### PR DESCRIPTION
**Pull request by drbh**
use literal event structure and added a helper function `calculate_reserves_to_remove`

### CODE REVIEW

**Comment by GopherJ** [comment]
hi @drbh what's the context of this one? Because the syntax is global, feel like if we would like to change, we should change for all pallets to make things consistent.

In TypeScript we should be able to do `const [..] = event` for having all those fields

**Comment by drbh** [comment]
Hey @GopherJ I only made the change because it makes the events easier to read in the code. I think we may want to use this syntax in all of the pallets but that can be a separate bigger refactor PR. Is there any reason we should not use the literal syntax?

I've removed the new syntax from this PR so we can merge the changes to the events. Thanks!

**Comment by GopherJ** [comment]
@drbh I just checked substrate it seems they also didn't use the new syntax yet. I think the current syntax is also ok as long as we have comments for every parameter.

**Comment by drbh** [comment]
@GopherJ okay sounds good. Thanks for checking 🙏

Please let me know if I should change anything else about the PR before merging

**Review by GopherJ — APPROVED** [review]

**Pull request merged**
