### PR TITLE
convert u128 to allowed FixedU128 return type

### PR DESCRIPTION
**Pull request by drbh**
RPC panics on u128 serialization. However FixedU128s are allowed

### CODE REVIEW

**Comment by drbh** [comment]
@GopherJ this PR fixes the issue with the `getBestRoute` RPC call. Currently the `u128` return type will cause the node to panic. Using a `FixedU128` resolves this issue and we should merge and deploy this ASAP to avoid any downtime issues

**Comment by drbh** [comment]
for reference this is the error that was occurring 
```
Thread 'tokio-runtime-worker' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)'
```

**Comment by drbh** [comment]
related frontend changes https://github.com/parallel-finance/parallel-js/pull/34

**Review by GopherJ — APPROVED** [review]

**Comment by GopherJ** [comment]
@drbh looks in parallel-js it should return `FixedU128` instead of `Balance` right?

**Comment by rocketman1997** [comment]
@drbh curios just change to `FixedU128` will resolve the serializable issue? Or should we wrap u128 as `NumberOrHex` like [this](https://github.com/paritytech/substrate/blob/22d40c761a985482f93bbbea5ba4199bdba74f8e/frame/transaction-payment/rpc/src/lib.rs#L144)

**Pull request merged**
