### PR TITLE
setup CI to generate benchmark weights

### LINKED ISSUE #106: setup CI to generate benchmark weights

### PR DESCRIPTION
**Pull request by ayushmishra2005**
resolves #106

### CODE REVIEW

**Comment by GopherJ** [comment]
@ayushmishra2005 it's running on github actions right? I would prefer it runs on our virtual machine which has the same perf as production one

**Comment by ayushmishra2005** [comment]
> @ayushmishra2005 it's running on github actions right? I would prefer it runs on our virtual machine which has the same perf as the production one, maybe you can use `scp` to push the binary to the weights server and then use `ssh` to run benchmark on it finally pull back the benchmark file.
> 
> also have you tested `EndBug/add-and-commit@v7` on your own fork? does it work well?

@GopherJ 

1) I want to test the script on github action first. After that, I would try it on a virtual machine. 

2) I tried this `EndBug/add-and-commit@v7` on my sample application https://github.com/ayushmishra2005/substrate-barcode-scanner/blob/master/.github/workflows/ci.yml and its working fine.

**Review by GopherJ — APPROVED** [review]

**Pull request closed without merging**
