### PR TITLE
Improve integration test&Move statemine to asset registry

### PR DESCRIPTION
**Pull request by yrong**
- [x] some integration tests to cover xcm transact call and also some refactor accordling
- [x] move statemine asset to asset registry
- [x] more tests

### CODE REVIEW

**Comment by yrong** [comment]
@GopherJ  would suggest we start the migration from statemine asset first, if we decide to do we can set storage in heiko reference params here 

https://github.com/parallel-finance/parallel/blob/de75818df4b542784bbb07eaab00c2652e741e16/runtime/heiko/src/lib.rs#L1285-L1296

then in the next upgrade window we have less work to do

**Comment by GopherJ** [comment]
> @GopherJ would suggest we start the migration from statemine asset first, if we decide to do we can set storage into asset-registry first reference params following
> 
> https://github.com/parallel-finance/parallel/blob/de75818df4b542784bbb07eaab00c2652e741e16/runtime/heiko/src/lib.rs#L1285-L1296
> 
> then in the next upgrade window we have less work to do

yes we can start from that

**Comment by GopherJ** [comment]
@yrong can our ksm_per_second function accept also decimals diff of the asset? so that we dont need to hardcode 1e6. we can read asset's deciamls from Assets module or we can also define foreign asset's decimals directly in `constants.rs`

**Comment by yrong** [comment]
> @yrong can our ksm_per_second function accept also decimals diff of the asset? so that we dont need to hardcode 1e6. we can read asset's deciamls from Assets module or we can also define foreign asset's decimals directly in `constants.rs`

@GopherJ  code above is just for hint and will be removed, we need to manually set it into storage as following
image
image


verified in polkadot-9230(v0.9.23 based) + statemine-900(polkadot-v0.9.19 based) which is the running version online
image

usdt could be transfered back and forth with no problem

**Review by GopherJ — APPROVED** [review]

**Pull request merged**
