### PR TITLE
Fix/handle overflows

### PR DESCRIPTION
**Pull request by c02fee**
`fn do_add_liquidity`

Existing implementation ( before BugUint)

| ideal_base_amount(x)    | ideal_quote_amount        | mul(y)            | sqrt(z) | sub(a)
| :--: | :--: | :--: |:--: |:--: |
| 2000                    |  1000                     | 2000000           | 1414    | 414
| 2000000000000000000000  |  1000000000000000000000   | None              | None    | None

### CODE REVIEW

**Comment by c02fee** [comment]
TODO's
- [x] Fix overflows happens in sub, mul, div, add.
- [ ] `T::Assets::transfer` does not support any values above `u128`.
- [ ]  Creates custom types to support U512

**Comment by c02fee** [comment]
Context 
T::Asset::transfer fails if amounts are greater than `u128`
Test data -> ideal_base_amount = 2_000_000_000_000_000_000_000

```
T::Assets::transfer(
            base_asset,
            who,
            &Self::account_id(),
            ideal_base_amount,      <---- greater than u128
            true,
        )
```
substrate->frame->assets->src->functions.rs

```
	// Maximum `amount` that can be passed into `can_withdraw` to result in a `WithdrawConsequence`
	// of `Success`.
	pub(super) fn reducible_balance(
		id: T::AssetId,
		who: &T::AccountId,
		keep_alive: bool,
	) -> Result<T::Balance, DispatchError> {
		let details = Asset::<T, I>::get(id).ok_or_else(|| Error::<T, I>::Unknown)?;
		ensure!(!details.is_frozen, Error::<T, I>::Frozen);

		let account = Account::<T, I>::get(id, who).ok_or(Error::<T, I>::NoAccount)?;
		ensure!(!account.is_frozen, Error::<T, I>::Frozen);

		let amount = if let Some(frozen) = T::Freezer::frozen_balance(id, who) {
			// Frozen balance: account CANNOT be deleted
			let required =
				frozen.checked_add(&details.min_balance).ok_or(ArithmeticError::Overflow)?;
			account.balance.saturating_sub(required)
		} else {
			let is_provider = false;
			let is_required = is_provider && !frame_system::Pallet::<T>::can_dec_provider(who);
			if keep_alive || is_required {
				// We want to keep the account around.
				account.balance.saturating_sub(details.min_balance)
			} else {
				// Don't care if the account dies
				account.balance
			}
		};
		Ok(amount.min(details.supply))

pub(super) fn prep_debit(
		id: T::AssetId,
		target: &T::AccountId,
		amount: T::Balance,
		f: DebitFlags,
	) -> Result<T::Balance, DispatchError> {
		let actual = Self::reducible_balance(id, target, f.keep_alive)?.min(amount);
		ensure!(f.best_effort || actual >= amount, Error::<T, I>::BalanceLow);   // Fails here 

		let conseq = Self::can_decrease(id, target, actual, f.keep_alive);
		let actual = match conseq.into_result() {
			Ok(dust) => actual.saturating_add(dust), //< guaranteed by reducible_balance
			Err(e) => {
				debug_assert!(false, "passed from reducible_balance; qed");
				return Err(e.into())
			},
		};

		Ok(actual)
	}
```

**Comment by c02fee** [comment]
Test case for loss of precision :- `do_add_liquidity_exact_amounts_should_work`  in `amm`


/*
Loss of precision happens here 
amount = `2_000_000_000_000_000_000_000`
actual = `1_999_999_999_999_999_999_999`
reducible_balance should return 2_000_000_000_000_000_000_000 for this scenario
*/

**Comment by c02fee** [comment]
Available Substrate Libraries 
* https://docs.substrate.io/rustdocs/latest/sp_core/struct.U256.html
* https://docs.substrate.io/rustdocs/latest/sp_core/uint/struct.U512.html

**Comment by c02fee** [comment]
@GopherJ There is a test which checks for precision which is ignored at the moment. Please let me know if its valid in our context . Thanks

**Comment by c02fee** [comment]
@drbh PR updated, cheers

**Review by drbh — APPROVED** [review]
LGTM 🥂 

@GopherJ what do you think?

**Pull request merged**
