### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by woshihahaha**
test-bench-bot

### CODE REVIEW

**Comment by woshihahaha** [comment]
benchmark pallet --help

**Comment by woshihahaha** [comment]
/benchmark runtime pallet --chain parallel-dev pallet_liquid_staking

**Comment by woshihahaha** [comment]
/benchmark runtime  --chain parallel-dev pallet pallet_liquid_staking

**Comment by woshihahaha** [comment]
/benchmark runtime pallet --chain=parallel-dev pallet_liquid_staking

**Comment by woshihahaha** [comment]
/benchmark  runtime --chain=parallel-dev pallet pallet_liquid_staking

**Comment by woshihahaha** [comment]
/benchmark runtime pallet pallet_liquid_staking --chain=parallel-dev

**Comment by c0ding** [comment]
/benchmark runtime pallet pallet_liquid_staking --chain=parallel-dev

**Comment by woshihahaha** [comment]
systemctl status parallel-bench-bot.service

**Pull request closed without merging**
